### PR TITLE
(maint) add symlink for acceptance to test

### PR DESCRIPTION
**Pull request by johnduarte**
This commit adds a symlink for acceptance to test in order to
provide a directory structure similar to `puppet-code`. This is
needed by the pe-client-tools integration pipeline because the
pipeline script is applied identically to each tool components
test suite.

[skip-ci]

### CODE REVIEW

**Comment by ajroetker** [comment]
@johnduarte Does this need to go on just the everett branch or should it go on the davis branch (stable) as well?

**Comment by johnduarte** [comment]
@ajroetker this should be applied to davis as well. Sigh. Thanks. Would you like me to close this PR and open one against stable that can be merged up? Or should we proceed with this one and cherry-pick it into stable?

**Comment by wkalt** [comment]
@johnduarte let's reopen and merge up

**Comment by johnduarte** [comment]
Closing in order to submit against stable branch.

**Pull request closed without merging**
